### ISSUE TITLE
Docs on interpreting the db?

### ISSUE THREAD

**Issue by reckoner165** [shockmonger/ragaDB#1]
I'm exploring the possibility of using this as the basis for a raag based sequencer. Is there somewhere I can learn how to access and interpret the csv files present in this repo?

**Comment by shockmonger** [comment]
Hi!
Definitely - I have also a json version of the dataset that is even better to work out of - i will update this repo soon in a day or two and text you!

**Comment by shockmonger** [comment]
@reckoner165 jsons and a short description in the README has been added! Please let me know if you need any more information!

**Comment by reckoner165** [comment]
Thanks!
